language: go
go:
  - "1.11.5"

git:
  depth: 10

sudo: required

before_install:
  - sudo apt-get update
  - sudo apt-get install node -y
  - go get -u -v github.com/gohugoio/hugo
  - npm install -g gulp
  - npm install -g travis-ci-cloudfront-invalidation

install:
  - npm install

script:
  - node index.js
  - hugo

before_deploy:
  - node index.js
  - hugo

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: $AWS_S3_BUCKET_DEV
    skip_cleanup: true
    local-dir: public
    acl: public_read
    on:
      branch: develop
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: $AWS_S3_BUCKET_PROD
    skip_cleanup: true
    local-dir: public
    acl: public_read
    on:
      branch: master

# after_deploy:
#   - if [[ $TRAVIS_BRANCH = "master" ]]; then travis-ci-cloudfront-invalidation -a $AWS_ACCESS_KEY_ID -s $AWS_SECRET_ACCESS_KEY -c $AWS_CLOUDFRONT_ID_PROD -i '/*' -b 'master' -p $TRAVIS_PULL_REQUEST; fi
