language: go
go:
- '1.11'
git:
  depth: 10
sudo: required

before_install:
- sudo apt-get update
- sudo apt-get install node -y
- sudo apt-get sshpass
- go get -u -v github.com/gohugoio/hugo

install:
- npm install

script:
- node index.js
- hugo

before_deploy:
- openssl aes-256-cbc -K $encrypted_34f7b1804be1_key -iv $encrypted_34f7b1804be1_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
- node index.js
- hugo

deploy:
- provider: script
  skip_cleanup: true
  script: sshpass -p $PASSWORD scp -r $TRAVIS_BUILD_DIR/public $USERNAME@$HOST:ccv/dev/travis_test
  on:
    branch: develop
