language: go
go:
- '1.11'
git:
  depth: 10
sudo: required
before_install:
- sudo apt-get update
- sudo apt-get install node -y
- go get -u -v github.com/gohugoio/hugo
install:
- npm install
script:
- node index.js
- hugo
