baseURL: http://ccv-website-dev.s3-website-us-east-1.amazonaws.com
languageCode: en-us
title: Brown Center for Computing and Visualization
theme: gb-theme

outputs:
  home:
    - html
    - rss
    - json

DefaultContentLanguage: en
canonifyURLs: true
relativeURLs: true

menu:
  main:
  - identifier: about
    name: About
    title: About
    url: /about/
    weight: 1
  - identifier: services
    name: Services
    title: Services
    url: /services/
    weight: 2
  - identifier: resources
    name: Resources
    title: Resources
    url: /resources/
    weight: 2
  - identifier: documentation
    name: User Manuals
    title: Documentation
    url: /documents/
    weight: 3
  - identifier: blog
    name: Blog
    title: Blog
    url: /blog/
    weight: 4

disableLanguages:
  - pt
languages:
  en:
    languageName: English
    weight: 1
    contentDir: content/english

  pt:
    languageName: Portuguese
    weight: 2
    contentDir: content/portuguese
