baseURL: https://datasci.brown.edu/ccv-dev #http://ccv-website-dev.s3-website-us-east-1.amazonaws.com
languageCode: en-us
title: Brown Center for Computing and Visualization
theme: gb-theme
permalinks:
  news: "/:year/:month/:slug/"

outputs:
  home:
    - html
    - rss
    - json

enableRobotsTXT: true
DefaultContentLanguage: en
canonifyURLs: true
relativeURLs: false

pygmentsCodefences: true

# Menu
menu:
  main:
  - identifier: home
    name: Home
    title: Home
    url: /
    weight: 1
  - identifier: about
    name: About
    title: About
    url: /about/
    weight: 2
  - identifier: services
    name: Services
    title: Services
    url: /services/
    weight: 3
  - identifier: documentation
    name: Documentation
    title: Documentation
    url: /documentation/
    weight: 5
  - identifier: news
    name: News
    title: News
    url: /news/
    weight: 6

params:
  contact:
    support: support@ccv.brown.edu
    discourse: https://discuss.ccv.brown.edu

# i18n
disableLanguages:
  - pt
languages:
  en:
    languageName: English
    weight: 1
    contentDir: content/english

  pt:
    languageName: Portuguese
    weight: 2
    contentDir: content/portuguese


# Taxonomies
taxonomies:
  tag: "tags"
  type: "types"
  category: "category"
