baseURL: http://ccv-website-dev.s3-website-us-east-1.amazonaws.com
languageCode: en-us
title: Brown Center for Computing and Visualization
theme: gb-theme

outputs:
  home:
    - html
    - rss
    - json

DefaultContentLanguage: en
canonifyURLs: true
relativeURLs: true

# Menu
menu:
  main:
  - identifier: home
    name: Home
    title: Home
    url: /
    weight: 1
  - identifier: about
    name: About
    title: About
    url: /about/
    weight: 2
  - identifier: services
    name: Services
    title: Services
    url: /services/
    weight: 3
  - identifier: resources
    name: Resources
    title: Resources
    url: /resources/
    weight: 4
  - identifier: documentation
    name: User Manuals
    title: User Manuals
    url: /user-manuals/
    weight: 5
  - identifier: blog
    name: Blog
    title: Blog
    url: /posts/
    weight: 6

# i18n
disableLanguages:
  - pt
languages:
  en:
    languageName: English
    weight: 1
    contentDir: content/english

  pt:
    languageName: Portuguese
    weight: 2
    contentDir: content/portuguese


# Taxonomies
taxonomies:
  tag: "tags"
  category: "category"
