baseURL: http://ccv-website-dev.s3-website-us-east-1.amazonaws.com
languageCode: en-us
title: Brown Center for Computing and Visualization
theme: gb-theme
DefaultContentLanguage: en
languages:
  en:
    languageName: English
    weight: 1
    contentDir: content/english
  pt:
    languageName: Portuguese
    weight: 2
    contentDir: content/portuguese
