languageCode: en-us
title: Brown Center for Computation and Visualization
theme: gb-theme
permalinks:
  news: "/:year/:month/:slug/"
googleAnalytics: UA-136333978-7
outputs:
  home:
    - html
    - rss
    - json

enableRobotsTXT: true
DefaultContentLanguage: en
canonifyURLs: true
relativeURLs: true

pygmentsCodefences: true

# Menu
menu:
  main:
  - identifier: home
    name: Home
    title: Home
    url: /
    weight: 1
  - identifier: about
    name: About
    title: About
    url: /about/
    weight: 2
  - identifier: services
    name: Services
    title: Services
    url: /services/
    weight: 3
  - identifier: facilities
    name: Facilities
    title: Facilities
    url: /facilities/
    weight: 5
  - identifier: documentation
    name: Documentation
    title: Documentation
    url: /documentation/
    weight: 6
  - identifier: news
    name: News
    title: News
    url: https://medium.com/brown-ccv
    weight: 7
  - identifier: events
    name: Events
    title: Events
    url: https://events.brown.edu/ccv/view/month
    weight: 8
  - identifier: ourwork
    name: Our Work
    title: "Our Work:"
    weight: 9
  - identifier: apps
    parent: ourwork
    name: Software
    title: Software
    url: /apps/
    weight: 10
  - identifier: workshops
    parent: ourwork
    name: Workshops
    title: Workshops
    url: /workshops/
    weight: 10

params:
  address: 180 George St, Providence RI 02906
  contact:
    support:
      text: Submit a ticket
      link: mailto:support@ccv.brown.edu
      fa: fas fa-ticket-alt
    discourse:
      text: Join the discussion!
      link: https://ask.cyberinfrastructure.org/c/brown-research-computing
      fa: fab fa-discourse
    feedback:
      text: Help us improve!
      link: https://docs.google.com/forms/d/e/1FAIpQLSdT00ZSXQh8vKbAMvc1xUoBfGtf2SU8bw5T3tIchKf03TgfbA/viewform?usp=sf_link
      fa: fas fa-star-half-alt
  githubLinks:
    ccvGithub: https://github.com/brown-ccv/
    cbcGithub: https://github.com/compbiocore/it

  covid:
    title: COVID-19 Updates
    lastUpdated: 03 April 2020
    text: |
      The Center for Computation and Visualization remains committed to supporting
      the computing needs of the Brown Research Community during this difficult time.
      In addition to the various platforms for compute and storage, CCV staff
      will continue to provide data science and consulting support as well as office hours and workshops.
      These will be done remotely, but will continue with the same regularity as was provided on campus.
      Onsite repairs and additions to hardware will be provided as safety permits.
      We are committed to supporting the research community throughout this pandemic.
      Anyone with specific questions or concerns should reach out to Thomas Serre,
      Faculty Director for CCV at thomas_serre@brown.edu, Linnea Wolfe, Operating Director for CCV
      at linnea_wolfe@brown.edu, or Paul Stey, Director of Data Science and Scientific Computing at paul_stey@brown.edu. 

      Furthermore, in partnership with the Office of the Vice President for Research, the Center for Computation and Visualization is 
      announcing the availability of HPC compute resources (condo) for use on the CCV cluster at no-cost for approved research. 
      In addition, we will be providing the JHU CSSE COVID-19 dataset with daily updates. Other public datasets that are needed may be 
      added on request, if reasonable. Please email support@ccv.brown.edu to ask for this service and CCV will work with OVPR to vet and approve the request.

      Thank you for your patience and continued use of CCV services.

# i18n
languages:
  en:
    languageName: English
    weight: 1
    contentDir: content/english
  pt:
    languageName: Portuguese
    weight: 2
    contentDir: content/portuguese
  zh:
    languageName: Chinese (Simplified)
    weight: 3
    contentDir: content/chinese


# Taxonomies
taxonomies:
  tag: "tags"
  type: "types"
  category: "category"
