baseURL: http://ccv-website-dev.s3-website-us-east-1.amazonaws.com
languageCode: en-us
title: Brown Center for Computing and Visualization
theme: gb-theme
DefaultContentLanguage: en
canonifyURLs: true
relativeURLs: true
disableLanguages:
  - pt
languages:
  en:
    languageName: English
    weight: 1
    contentDir: content/english
    menu:
      main:
      - identifier: about
        name: About
        title: About
        url: /about/
        weight: 1
      - identifier: services
        name: Services
        title: Services
        url: /services/
        weight: 2
      - identifier: documentation
        name: Documentation
        title: Documentation
        url: /documents/
        weight: 3
      - identifier: blog
        name: Blog
        title: Blog
        url: /blog/
        weight: 4


  pt:
    languageName: Portuguese
    weight: 2
    contentDir: content/portuguese
    menu:
      main:
      - identifier: sobre
        name: Sobre
        title: sobre section
        url: /about/
        weight: 1
      - identifier: serviços
        name: Serviços
        title: serviços section
        url: /services/
        weight: 2
      - identifier: documentação
        name: Documentação
        title: documentação section
        url: /documents/
        weight: 3
      - identifier: blog
        name: Blog
        title: blog section
        url: /blog/
        weight: 4
