---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: document
  path: content/english/about/_index.md
  label: About
  match: "**/*"
- type: document
  path: config.yml
  label: Config
- type: directory
  path: content/english
  label: English
  create: all
  match: "**/*"
- type: directory
  path: content/portuguese
  label: Portuguese
  create: all
  match: "**/*"
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: hugo -E -F -D -b $DEPLOY_URL -d public
  publish_command: hugo -d public
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.53
  publish_env:
  - HUGO_ENV=production
  - HUGO_VERSION=0.53
  preview_output_directory: public
  output_directory: public
version: '0.53'
