---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: data
  label: data
  create: all
  match: "**/*"
  exclude: events.json
- type: document
  path: config.yml
  label: Site Configuration
- type: directory
  path: content/english
  label: Content
  create: all
  match: "**/*"
  exclude: search.md
- type: directory
  path: data
  label: Data
  create: all
  match: "**/*"
  exclude: events.json
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: hugo -E -F -D -b $DEPLOY_URL -d public
  publish_command: hugo -d public
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.53
  publish_env:
  - HUGO_ENV=production
  - HUGO_VERSION=0.53
  preview_output_directory: public
  output_directory: public
version: '0.53'
