name: PR Commenter and Labeler - Release

on:
  pull_request:
    branches:
      - production

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Get PR Change Types
      id: pr_type
      uses: brown-ccv/gh-actions/get-pr-type@main
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Release Review Comment PR
      uses: brown-ccv/gh-actions/comment-pr-checklist@main
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        message_id: "Release"
        message_file: '.github/CODE_REVIEW/release.md'
