name: PR Commenter

on:
  pull_request:
    branch:
      - develop


jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Comment on PR
      uses: brown-ccv/gh-actions/comment-pr-checklist@pr-checklist
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
